/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppIcon: typeof import('./src/components/AppIcon.vue')['default']
    'IconMdi:moonWaningCrescent': typeof import('~icons/mdi/moon-waning-crescent')['default']
    IconMdiBellOutline: typeof import('~icons/mdi/bell-outline')['default']
    IconMdiFullscreen: typeof import('~icons/mdi/fullscreen')['default']
    IconMdiFullscreenExit: typeof import('~icons/mdi/fullscreen-exit')['default']
    IconMdiHelpCircleOutline: typeof import('~icons/mdi/help-circle-outline')['default']
    IconMdiWhiteBalanceSunny: typeof import('~icons/mdi/white-balance-sunny')['default']
    IconTemplate: typeof import('./src/components/template/icon-template.vue')['default']
    NavLink: typeof import('./src/components/NavLink.vue')['default']
    PageContainer: typeof import('./src/components/PageContainer.vue')['default']
    PageContainerFull: typeof import('./src/components/PageContainerFull.vue')['default']
    PageContainerSplit: typeof import('./src/components/PageContainerSplit.vue')['default']
    PageSection: typeof import('./src/components/PageSection.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WBorder: typeof import('./src/components/w-border/w-border.vue')['default']
    WContainer: typeof import('./src/components/w-container/w-container.vue')['default']
    WSection: typeof import('./src/components/w-section/w-section.vue')['default']
    WSection1: typeof import('./src/components/WSection1.vue')['default']
  }
}
